imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

# Symfony Framework
framework:
    translator:      { fallbacks: [ "%locale%" ] }
    validation:      { enable_annotations: true }
    default_locale:  "%locale%"
    secret:          "%secret%"
    form:            ~
    csrf_protection: ~
    trusted_hosts:   ~
    trusted_proxies: ~
    fragments:       ~
    router:
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    templating:
        engines: [ "twig" ]
    session:
        name:        LTSESSID
        handler_id:  ~
    http_method_override: true

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "bootstrap_3_layout.html.twig"
    globals:
        admin_tag_version:        "v1.0.00"
        google_analytics_enabled: "%google_analytics_enabled%"
        google_analytics_account: "%google_analytics_account%"
        google_maps_api_key:      "%google_maps_api_key%"

# Doctrine Configuration
doctrine:
    dbal:
        server_version: "%database_server_version%"
        driver:         "%database_driver%"
        host:           "%database_host%"
        port:           "%database_port%"
        dbname:         "%database_name%"
        user:           "%database_user%"
        password:       "%database_password%"
        charset:        UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy:             doctrine.orm.naming_strategy.underscore
        auto_mapping:                true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
